# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hb81wHhP_dX7D0HU6e7bMstHFr88oqFN
"""

import math

#input a 
#input b
print("Digite o valor do intevalo [a,b]:\n")
a = float(input("a: "))
b = float(input("b: "))

#input erro
erro = float(input("\nDigite o valor da precisao desejada: "))
1

#input função
fun = input("f(x) = ")

def f(val):
  funval = eval(fun.replace('x', 'val'))
  return funval

#compara os sinais dos valores
def compara(val1, val2):
  if val1 * val2 == 0:
    return 0
  if val1 * val2 < 0:
    return -1
  else:
    return 1

#metodo da bisseccao
if compara(f(a), f(b)) > 0:
  print("Não há raíz neste intervalo.")

else:
  k=0
  while math.fabs(b-a) > erro:
    #novo intervalo
    ni = (a+b)/2

    if f(ni) == 0:
      print(f"A raíz é f({ni:.4f})=0")
      break
    
    if compara(f(a), f(ni)) < 0:
      b = ni

    else:
      a = ni
    k=k+1
  print(f"\nO valor mais próximo da raiz tal que |b-a|< e é f({ni:.4f})={f(ni):.7f}\nNo intervalo [{a:.4f},{b:.4f}], com ",k," iterações.")